server {
    listen 80;
    listen [::]:80;
    server_name hobbit.orfeasa.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://limited.orfeasa.com$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name hobbit.orfeasa.com;

    ssl_certificate /etc/letsencrypt/live/hobbit.orfeasa.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hobbit.orfeasa.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    server_tokens off;

    location = /sw.js {
        alias /home/orfeas/apps/mtg-limited-guides/current/retired/hobbit-sw.js;
        default_type application/javascript;
        expires -1;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }

    location / {
        return 301 https://limited.orfeasa.com$request_uri;
    }
}
