#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.dirname(here);
const dataDir = path.join(root, "data");
const publicDir = path.join(root, "public");
const readJson = (file) => JSON.parse(fs.readFileSync(path.join(dataDir, file), "utf8"));

const manifest = readJson("sets.json");
const pickOrder = readJson("hobbit_pick_order.json");
const artIds = readJson("hobbit_art_ids.json");
const colorData = readJson("hobbit_colors.json");
const cardStats = readJson("hobbit_card_stats.json");

const winRate = (wins, games) => Number.isFinite(wins) && Number.isFinite(games) && games > 0
  ? Math.round((wins / games) * 1000) / 10
  : null;

const bandForTier = (tier) => {
  if (["S", "A+", "A", "A-"].includes(tier)) return "top";
  if (["B+", "B", "B-"].includes(tier)) return "strong";
  if (["C+", "C", "C-"].includes(tier)) return "playable";
  if (["D+", "D", "D-", "F"].includes(tier)) return "filler";
  return "unrated";
};

const hobbitCards = [];
let rank = 1;
for (const section of pickOrder.sections) {
  for (const name of section.names) {
    const stats = cardStats.cards[name];
    if (!stats) throw new Error(`Missing Hobbit card statistics for ${name}`);
    hobbitCards.push({
      id: `hob-${rank}`,
      rank,
      tier: section.tier,
      band: bandForTier(section.tier),
      name,
      color: colorData.colors[name],
      image: `assets/cards/${artIds[rank - 1]}.jpg`,
      trainingImage: `assets/cards-large/${artIds[rank - 1]}.jpg`,
      stats: {
        inHandWinRate: winRate(stats.in_hand_wins, stats.in_hand_games),
        inHandGames: stats.in_hand_games,
        openingHandWinRate: winRate(stats.opening_hand_wins, stats.opening_hand_games),
        openingHandGames: stats.opening_hand_games,
        avgLastOffered: stats.avg_last_offered,
      },
    });
    rank += 1;
  }
}

if (hobbitCards.length !== 188 || artIds.length !== 188) {
  throw new Error(`Expected 188 Hobbit cards and art IDs; got ${hobbitCards.length} and ${artIds.length}`);
}

const missingColors = hobbitCards.filter((card) => !card.color);
if (missingColors.length > 0) {
  throw new Error(`Missing color identity for: ${missingColors.map((card) => card.name).join(", ")}`);
}

if (cardStats.total_matches < Number(String(pickOrder.total_matches).replace(/,/g, ""))) {
  throw new Error("Hobbit statistics snapshot is older than the pick-order evidence");
}

const setAdapters = {
  "hobbit-ranking": () => ({ cards: hobbitCards, previewCapturedAt: null }),
  preview: (set) => {
    if (!set.dataFile) throw new Error(`Preview set ${set.id} is missing dataFile`);
    const preview = readJson(set.dataFile);
    if (preview.set !== set.code) {
      throw new Error(`Preview data ${set.dataFile} contains ${preview.set}, expected ${set.code}`);
    }
    return {
      cards: preview.cards.map((card) => ({ ...card, rank: null, tier: null, band: "unrated" })),
      previewCapturedAt: preview.capturedAt,
    };
  },
};

const sets = manifest.sets.map((set) => {
  const adapt = setAdapters[set.adapter];
  if (!adapt) throw new Error(`No card-data adapter configured for set ${set.id}`);
  const { cards, previewCapturedAt } = adapt(set);
  return {
    ...set,
    cardCount: cards.length,
    previewCapturedAt,
    cards,
  };
});

const dataScript = `/* Generated by scripts/build-data.mjs. */\nwindow.LIMITED_PREP_DATA = ${JSON.stringify({ version: manifest.version, sets }, null, 2)};\n`;
fs.writeFileSync(path.join(publicDir, "data.js"), dataScript);

const cacheFiles = [
  "./",
  "./index.html",
  "./styles.css",
  "./data.js",
  "./app.js",
  "./manifest.webmanifest",
  "./assets/icon.svg",
  "./assets/icon-32.png",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/apple-touch-icon.png",
  "./assets/fonts/Alegreya-SemiBold.ttf",
  "./assets/fonts/Alegreya-Bold.ttf",
  "./assets/fonts/AtkinsonHyperlegibleNext-Regular.ttf",
  "./assets/fonts/AtkinsonHyperlegibleNext-Bold.ttf",
  "./assets/fonts/BarlowCondensed-Black.ttf",
  ...sets.flatMap((set) => set.cards.map((card) => `./${card.image}`)),
];

const cacheDigest = crypto.createHash("sha256");
for (const file of cacheFiles) {
  if (file === "./") continue;
  const relativePath = file.replace(/^\.\//, "");
  cacheDigest.update(file);
  cacheDigest.update(fs.readFileSync(path.join(publicDir, relativePath)));
}
const cacheVersion = cacheDigest.digest("hex").slice(0, 12);

const serviceWorker = `/* Generated static cache manifest. */
const CACHE = "limited-prep-${cacheVersion}";
const ASSETS = ${JSON.stringify(cacheFiles, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request).then((response) => {
      const copy = response.clone();
      caches.open(CACHE).then((cache) => cache.put(event.request, copy));
      return response;
    }))
  );
});
`;
fs.writeFileSync(path.join(publicDir, "sw.js"), serviceWorker);

console.log(`Generated ${sets.length} sets, ${sets.reduce((sum, set) => sum + set.cards.length, 0)} cards, and ${cacheFiles.length} cached assets.`);
